# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AECS
email: contact@aecs.asso.fr
description: Site web de l'AECS
baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
front-page-posts: 12

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: AECS-17
# twitter_username: andrewbanchich
facebook_URL: https://www.facebook.com/aecsparis17/
# instagram_username: andrewbanchich
# dribbble_username: andrewbanchich
# 500px_username: andrewbanchich
phone:

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
